chore: created docker build/bake system for creation of all required images

diff --git a/scripts/spack b/scripts/spack
--- a/scripts/spack
+++ b/scripts/spack
@@ -177,6 +177,13 @@ spack_load_dependencies ()
 
 spack_install_dependencies ()
 {
+
+	
+	if $(command -v git) 
+	then 
+		echo "Git is required but wasn't found!" && exit 1 
+	fi
+
 	# FIXME does not fail if Git is not installed
 	if spack_clone
 	then
