ci: move to containers

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -33,207 +33,211 @@ jobs:
       - name: Check shell scripts
         run: |
           ./scripts/check.sh
-  dependencies:
-    name: Dependencies
-    runs-on: ${{ matrix.os.dist }}
-    timeout-minutes: 180
-    strategy:
-      fail-fast: false
-      matrix:
-        os:
-          - dist: ubuntu-24.04
-            compiler: gcc
-            compiler_version: 13.2.0
-          - dist: ubuntu-24.04
-            compiler: clang
-            compiler_version: 18.1.3
-          - dist: ubuntu-22.04
-            compiler: gcc
-            compiler_version: 11.4.0
-          - dist: ubuntu-22.04
-            compiler: clang
-            compiler_version: 14.0.0
-          - dist: ubuntu-20.04
-            compiler: gcc
-            compiler_version: 9.4.0
-          - dist: ubuntu-20.04
-            compiler: clang
-            compiler_version: 11.0.0
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          persist-credentials: false
-          show-progress: false
-      - name: Cache dependencies
-        id: cache
-        uses: actions/cache@v4
-        with:
-          path: dependencies
-          key: ${{ matrix.os.dist }}-${{ matrix.os.compiler }}-${{ matrix.os.compiler_version }}-${{ hashFiles('scripts/spack', 'scripts/install-dependencies.sh') }}
-      - name: Install dependencies
-        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
-        env:
-          JULEA_SPACK_COMPILER: ${{ matrix.os.compiler }}@${{ matrix.os.compiler_version }}
-        run: |
-          ./scripts/install-dependencies.sh
-  dependencies-containers:
-    name: Dependencies (Containers)
-    runs-on: ubuntu-24.04
-    container: ${{ matrix.os.registry }}/${{ matrix.os.image }}
-    timeout-minutes: 180
-    strategy:
-      fail-fast: false
-      matrix:
-        os:
-          - image: ubuntu:24.04
-            registry: docker.io/library
-            compiler: gcc
-            compiler_version: 13.2.0
-          - image: ubuntu:24.04
-            registry: docker.io/library
-            compiler: clang
-            compiler_version: 18.1.3
-          - image: ubuntu:22.04
-            registry: docker.io/library
-            compiler: gcc
-            compiler_version: 11.4.0
-          - image: ubuntu:22.04
-            registry: docker.io/library
-            compiler: clang
-            compiler_version: 14.0.0
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          persist-credentials: false
-          show-progress: false
-      - name: Install packages
-        if: ${{ matrix.os.image == 'ubuntu:24.04' || matrix.os.image == 'ubuntu:22.04' }}
-        run: |
-          apt update
-          apt --yes --no-install-recommends install build-essential zstd
-          apt --yes --no-install-recommends install ca-certificates git gnupg patchelf python3 unzip
-          if test "${{ matrix.os.compiler }}" = 'clang'
-          then
-            apt --yes --no-install-recommends install clang
+  # dependencies:
+  #   name: Dependencies
+  #   runs-on: ${{ matrix.os.dist }}
+  #   timeout-minutes: 180
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os:
+  #         - dist: ubuntu-24.04
+  #           compiler: gcc
+  #           compiler_version: 13.2.0
+  #         - dist: ubuntu-24.04
+  #           compiler: clang
+  #           compiler_version: 18.1.3
+  #         - dist: ubuntu-22.04
+  #           compiler: gcc
+  #           compiler_version: 11.4.0
+  #         - dist: ubuntu-22.04
+  #           compiler: clang
+  #           compiler_version: 14.0.0
+  #         - dist: ubuntu-20.04
+  #           compiler: gcc
+  #           compiler_version: 9.4.0
+  #         - dist: ubuntu-20.04
+  #           compiler: clang
+  #           compiler_version: 11.0.0
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #       with:
+  #         persist-credentials: false
+  #         show-progress: false
+  #     - name: Cache dependencies
+  #       id: cache
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: dependencies
+  #         key: ${{ matrix.os.dist }}-${{ matrix.os.compiler }}-${{ matrix.os.compiler_version }}-${{ hashFiles('scripts/spack', 'scripts/install-dependencies.sh') }}
+  #     - name: Install dependencies
+  #       if: ${{ steps.cache.outputs.cache-hit != 'true' }}
+  #       env:
+  #         JULEA_SPACK_COMPILER: ${{ matrix.os.compiler }}@${{ matrix.os.compiler_version }}
+  #       run: |
+  #         ./scripts/install-dependencies.sh
+  # dependencies-containers:
+  #   name: Dependencies (Containers)
+  #   runs-on: ubuntu-24.04
+  #   container: ${{ matrix.os.registry }}/${{ matrix.os.image }}
+  #   timeout-minutes: 180
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os:
+  #         - image: ubuntu:24.04
+  #           registry: docker.io/library
+  #           compiler: gcc
+  #           compiler_version: 13.2.0
+  #         - image: ubuntu:24.04
+  #           registry: docker.io/library
+  #           compiler: clang
+  #           compiler_version: 18.1.3
+  #         - image: ubuntu:22.04
+  #           registry: docker.io/library
+  #           compiler: gcc
+  #           compiler_version: 11.4.0
+  #         - image: ubuntu:22.04
+  #           registry: docker.io/library
+  #           compiler: clang
+  #           compiler_version: 14.0.0
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #       with:
+  #         persist-credentials: false
+  #         show-progress: false
+  #     - name: Install packages
+  #       if: ${{ matrix.os.image == 'ubuntu:24.04' || matrix.os.image == 'ubuntu:22.04' }}
+  #       run: |
+  #         apt update
+  #         apt --yes --no-install-recommends install build-essential zstd
+  #         apt --yes --no-install-recommends install ca-certificates git gnupg patchelf python3 unzip
+  #         if test "${{ matrix.os.compiler }}" = 'clang'
+  #         then
+  #           apt --yes --no-install-recommends install clang
 
-            if test "${{ matrix.os.image }}" = 'ubuntu:24.04'
-            then
-              apt --yes --no-install-recommends install libclang-rt-dev
-            fi
-          fi
-      - name: Cache dependencies
-        id: cache
-        uses: actions/cache@v4
-        with:
-          path: /dependencies
-          key: ${{ matrix.os.image }}-${{ matrix.os.compiler }}-${{ matrix.os.compiler_version }}-${{ hashFiles('scripts/spack', 'scripts/install-dependencies.sh') }}
-      - name: Install dependencies
-        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
-        env:
-          JULEA_SPACK_COMPILER: ${{ matrix.os.compiler }}@${{ matrix.os.compiler_version }}
-          JULEA_SPACK_DIR: /dependencies
-        run: |
-          ./scripts/install-dependencies.sh
-  build:
-    name: Build
-    needs: dependencies
-    runs-on: ${{ matrix.os.dist }}
-    timeout-minutes: 60
-    strategy:
-      fail-fast: false
-      matrix:
-        os:
-          - dist: ubuntu-24.04
-            compiler: gcc
-            compiler_version: 13.2.0
-          - dist: ubuntu-24.04
-            compiler: clang
-            compiler_version: 18.1.3
-          - dist: ubuntu-22.04
-            compiler: gcc
-            compiler_version: 11.4.0
-          - dist: ubuntu-22.04
-            compiler: clang
-            compiler_version: 14.0.0
-          - dist: ubuntu-20.04
-            compiler: gcc
-            compiler_version: 9.4.0
-          - dist: ubuntu-20.04
-            compiler: clang
-            compiler_version: 11.0.0
-        dependencies: [system, spack]
-        exclude:
-          # libfabric is too old on Ubuntu 20.04
-          - os:
-              dist: ubuntu-20.04
-            dependencies: system
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          persist-credentials: false
-          show-progress: false
-      - name: Clean up system packages
-        # We need to remove glib-network, otherwise libproxy might cause crashes.
-        run: |
-          sudo apt --yes purge glib-networking
-          sudo apt --yes --purge autoremove
-          sudo aa-remove-unknown || true
-      - name: Install dependencies
-        if: ${{ matrix.dependencies == 'system' }}
-        run: |
-          sudo apt update || true
-          sudo apt --yes --no-install-recommends install ninja-build pkgconf libglib2.0-dev libbson-dev libfabric-dev libgdbm-dev liblmdb-dev libsqlite3-dev libleveldb-dev libmongoc-dev libmariadb-dev librocksdb-dev libfuse3-dev libopen-trace-format-dev librados-dev
-          if test "${{ matrix.os.dist }}" != 'ubuntu-20.04'
-          then
-            sudo apt --yes --no-install-recommends install meson
-          else
-            sudo apt --yes --no-install-recommends install python3 python3-pip python3-setuptools python3-wheel
-            sudo pip3 install meson
-          fi
-      - name: Cache dependencies
-        id: cache
-        if: ${{ matrix.dependencies == 'spack' }}
-        uses: actions/cache/restore@v4
-        with:
-          path: dependencies
-          key: ${{ matrix.os.dist }}-${{ matrix.os.compiler }}-${{ matrix.os.compiler_version }}-${{ hashFiles('scripts/spack', 'scripts/install-dependencies.sh') }}
-      - name: Check dependencies
-        if: ${{ matrix.dependencies == 'spack' && steps.cache.outputs.cache-hit != 'true' }}
-        run: |
-          exit 1
-      - name: Configure, build and install
-        env:
-          CC: ${{ matrix.os.compiler }}
-        run: |
-          ./scripts/ci/build.sh release "${{ matrix.dependencies }}"
+  #           if test "${{ matrix.os.image }}" = 'ubuntu:24.04'
+  #           then
+  #             apt --yes --no-install-recommends install libclang-rt-dev
+  #           fi
+  #         fi
+  #     - name: Cache dependencies
+  #       id: cache
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: /dependencies
+  #         key: ${{ matrix.os.image }}-${{ matrix.os.compiler }}-${{ matrix.os.compiler_version }}-${{ hashFiles('scripts/spack', 'scripts/install-dependencies.sh') }}
+  #     - name: Install dependencies
+  #       if: ${{ steps.cache.outputs.cache-hit != 'true' }}
+  #       env:
+  #         JULEA_SPACK_COMPILER: ${{ matrix.os.compiler }}@${{ matrix.os.compiler_version }}
+  #         JULEA_SPACK_DIR: /dependencies
+  #       run: |
+  #         ./scripts/install-dependencies.sh
+  # build:
+  #   name: Build
+  #   needs: dependencies
+  #   runs-on: ${{ matrix.os.dist }}
+  #   timeout-minutes: 60
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os:
+  #         - dist: ubuntu-24.04
+  #           compiler: gcc
+  #           compiler_version: 13.2.0
+  #         - dist: ubuntu-24.04
+  #           compiler: clang
+  #           compiler_version: 18.1.3
+  #         - dist: ubuntu-22.04
+  #           compiler: gcc
+  #           compiler_version: 11.4.0
+  #         - dist: ubuntu-22.04
+  #           compiler: clang
+  #           compiler_version: 14.0.0
+  #         - dist: ubuntu-20.04
+  #           compiler: gcc
+  #           compiler_version: 9.4.0
+  #         - dist: ubuntu-20.04
+  #           compiler: clang
+  #           compiler_version: 11.0.0
+  #       dependencies: [system, spack]
+  #       exclude:
+  #         # libfabric is too old on Ubuntu 20.04
+  #         - os:
+  #             dist: ubuntu-20.04
+  #           dependencies: system
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #       with:
+  #         persist-credentials: false
+  #         show-progress: false
+  #     - name: Clean up system packages
+  #       # We need to remove glib-network, otherwise libproxy might cause crashes.
+  #       run: |
+  #         sudo apt --yes purge glib-networking
+  #         sudo apt --yes --purge autoremove
+  #         sudo aa-remove-unknown || true
+  #     - name: Install dependencies
+  #       if: ${{ matrix.dependencies == 'system' }}
+  #       run: |
+  #         sudo apt update || true
+  #         sudo apt --yes --no-install-recommends install ninja-build pkgconf libglib2.0-dev libbson-dev libfabric-dev libgdbm-dev liblmdb-dev libsqlite3-dev libleveldb-dev libmongoc-dev libmariadb-dev librocksdb-dev libfuse3-dev libopen-trace-format-dev librados-dev
+  #         if test "${{ matrix.os.dist }}" != 'ubuntu-20.04'
+  #         then
+  #           sudo apt --yes --no-install-recommends install meson
+  #         else
+  #           sudo apt --yes --no-install-recommends install python3 python3-pip python3-setuptools python3-wheel
+  #           sudo pip3 install meson
+  #         fi
+  #     - name: Cache dependencies
+  #       id: cache
+  #       if: ${{ matrix.dependencies == 'spack' }}
+  #       uses: actions/cache/restore@v4
+  #       with:
+  #         path: dependencies
+  #         key: ${{ matrix.os.dist }}-${{ matrix.os.compiler }}-${{ matrix.os.compiler_version }}-${{ hashFiles('scripts/spack', 'scripts/install-dependencies.sh') }}
+  #     - name: Check dependencies
+  #       if: ${{ matrix.dependencies == 'spack' && steps.cache.outputs.cache-hit != 'true' }}
+  #       run: |
+  #         exit 1
+  #     - name: Configure, build and install
+  #       env:
+  #         CC: ${{ matrix.os.compiler }}
+  #       run: |
+  #         ./scripts/ci/build.sh release "${{ matrix.dependencies }}"
+  
+  dependencies: 
+    uses: ./.github/workflows/containers.yml
   tests:
     name: Tests
     needs: dependencies
-    runs-on: ${{ matrix.os.dist }}
+    runs-on: ubuntu-latest
+    container: ghcr.io/finnhering/julea-${{ matrix.dependencies }}:${{ matrix.os.dist }}-${{ matrix.os.compiler }}-${{ matrix.os.compiler }}
     timeout-minutes: 60
     strategy:
       fail-fast: false
       matrix:
         os:
-          - dist: ubuntu-24.04
+          - dist: ubuntu-24-04
             compiler: gcc
             compiler_version: 13.2.0
-          - dist: ubuntu-24.04
+          - dist: ubuntu-24-04
             compiler: clang
             compiler_version: 18.1.3
-          - dist: ubuntu-22.04
+          - dist: ubuntu-22-04
             compiler: gcc
             compiler_version: 11.4.0
-          - dist: ubuntu-22.04
+          - dist: ubuntu-22-04
             compiler: clang
             compiler_version: 14.0.0
-          - dist: ubuntu-20.04
+          - dist: ubuntu-20-04
             compiler: gcc
             compiler_version: 9.4.0
-          - dist: ubuntu-20.04
+          - dist: ubuntu-20-04
             compiler: clang
             compiler_version: 11.0.0
         dependencies: [system, spack]
@@ -306,7 +310,7 @@ jobs:
           persist-credentials: false
           show-progress: false
       - name: Fix mmap_rnd_bits
-        if: ${{ matrix.os.dist == 'ubuntu-22.04' }}
+        if: ${{ matrix.os.dist == 'ubuntu-22-04' }}
         # FIXME https://github.com/actions/runner-images/issues/9491
         run: |
           sudo sysctl vm.mmap_rnd_bits=28
@@ -331,17 +335,17 @@ jobs:
             sudo apt --yes --no-install-recommends install python3 python3-pip python3-setuptools python3-wheel
             sudo pip3 install meson
           fi
-      - name: Cache dependencies
-        id: cache
-        if: ${{ matrix.dependencies == 'spack' }}
-        uses: actions/cache/restore@v4
-        with:
-          path: dependencies
-          key: ${{ matrix.os.dist }}-${{ matrix.os.compiler }}-${{ matrix.os.compiler_version }}-${{ hashFiles('scripts/spack', 'scripts/install-dependencies.sh') }}
-      - name: Check dependencies
-        if: ${{ matrix.dependencies == 'spack' && steps.cache.outputs.cache-hit != 'true' }}
-        run: |
-          exit 1
+      # - name: Cache dependencies
+      #   id: cache
+      #   if: ${{ matrix.dependencies == 'spack' }}
+      #   uses: actions/cache/restore@v4
+      #   with:
+      #     path: dependencies
+      #     key: ${{ matrix.os.dist }}-${{ matrix.os.compiler }}-${{ matrix.os.compiler_version }}-${{ hashFiles('scripts/spack', 'scripts/install-dependencies.sh') }}
+      # - name: Check dependencies
+      #   if: ${{ matrix.dependencies == 'spack' && steps.cache.outputs.cache-hit != 'true' }}
+      #   run: |
+      #     exit 1
       - name: Configure and build
         env:
           CC: ${{ matrix.os.compiler }}
